CREATE DATABASE IF NOT EXISTS workflow_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE workflow_db;

CREATE TABLE IF NOT EXISTS work_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    requester VARCHAR(100) NOT NULL,
    department VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
